### PR TITLE
fix: OG All files failed on one invalid relationship BED-6589

### LINKED ISSUE #1897: Bug: Error "1 File(s) failed to ingest as JSON Content" when importing with netexec or rusthound-ce as ingestors
## Description:
When uploading data collected from netexec or rusthound-ce I get the error "1 File(s) failed to ingest as JSON Content". I get the error even if I upload the whole .zip file or the files unzipped. Unfortunately I only have a domain user with no access to a domain machine to try the windows ingestors from a domain joined pc.  I have reinstalled all programs and the issue persists.   

*A clear and concise description of the bug you're encountering.*

### Are you intending to fix this bug?

*Please indicate "yes" or "no".*
No

## Component(s) Affected:

- Data Collector (Other)

## Steps to Reproduce:

Commands used to upload:

rusthound-ce --domain domain.local -u marcus -p 'Password' 

netexec ldap domain.local -u marcus -p 'Password' --bloodhound --collection All --dns-server 192.168.210.10

Then just upload to GUI. 

## Expected Behavior:
To ingest the data correctly. 

## Actual Behavior:
Error: 1 File(s) failed to ingest as JSON Content

## Screenshots/Code Snippets/Sample Files:

Image

## Environment Information:

BloodHound: 8.1.1

Collector: netexec 1.4.0 - SmoothOperator - 027e5208 - 940 /  rusthound-ce 2.4.0

OS: Kali VERSION_ID="2025.2"

Docker (if using Docker):  26.1.5+dfsg1, build a72d7cd

### PR DESCRIPTION
**Pull request by AD7ZJ**
## Description

Do not report unresolved relationships in an opengraph json file as failure of the entire file. 

## Motivation and Context

Resolves https://specterops.atlassian.net/browse/BED-6589
Closes #1897

## How Has This Been Tested?

Tested locally using a simple OG file that has some valid and invalid edges, referencing the AD example dataset. This file can be found in the ticket. 

## Screenshots (optional):
Now when you upload a file with some invalid edges, the ingest will report as "partially complete" 
image

An additional field `warnings` has been added to the response for the endpoint `/api/v2/file-upload/<job-id>/completed-tasks` . The UI should be updated to surface this additional field, with a different status color for warnings vs errors. 

image

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have met the contributing prerequisites
  - Assigned myself to this PR
  - Added the appropriate labels
  - Associated an issue: https://github.com/SpecterOps/BloodHound/issues/672
  - Read the Contributing guide: https://github.com/SpecterOps/BloodHound/wiki/Contributing
- [x] I have ensured that related documentation is up-to-date
  - Open API docs
  - Code comments (GoDocs / JSDocs)
- [x] I have followed proper test practices
  - Added/updated tests to cover my changes
  - All new and existing tests passed

## Summary by CodeRabbit

* **New Features**
  - Distinguish user-data errors from internal errors in ingestion reporting.
  - Track and report partial ingestion failures; jobs can be marked partially complete.
  - Persist warnings from ingestion tasks with completed task records.
* **Tests**
  - API test updated to include partial_failed_files in job responses.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: cmd/api/src/services/graphify/tasks.go [hunk 1]
```diff
@@ -179,7 +180,10 @@ func (s *GraphifyService) ProcessIngestFile(ic *IngestContext, task model.Ingest
 
 				if err := processSingleFile(ic.Ctx, data, ic, readOpts); err != nil {
 					var graphifyError errorlist.Error
-					if ok := errors.As(err, &graphifyError); ok {
+					var userDataErr errorlist.IngestUserDataError
+					if ok := errors.As(err, &userDataErr); ok {
+						fileData[i].UserDataErrs = append(fileData[i].UserDataErrs, userDataErr.Error())
+					} else if ok := errors.As(err, &graphifyError); ok {
```
Comment (wes-mil) [inline cmd/api/src/services/graphify/tasks.go]: I think unfortunately, this is an insufficient method for handling the error. This logic would indicate that we can _only_ have an `IngestUserDataError` or a `GraphifyError`, and these things have definitely both happen. 

It's going to be somewhat ugly, but I think we need to embed the `IngestUserDataError` into the `GraphifyError` list and then loop through the the `GraphifyError` out here to see if any of the errors are of type `IngestUserDataError`. 

I agree with @superlinkx that this design isn't great (and unfortunately I'm the one that designed it this way :smile:), but the effort to change is really large

File: packages/go/errorlist/error.go [hunk 2]
```diff
@@ -41,7 +42,12 @@ func (s ErrorBuilder) Build() error {
 	if len(s.Errors) == 0 {
 		return nil
 	} else {
-		return Error(s)
+		// wrap errors so they can be differentiated further up the call chain
+		err := s.Errors[0]
+		for _, e := range s.Errors[1:] {
+			err = fmt.Errorf("%w; %v", err, e)
+		}
+		return err
```
Comment (wes-mil) [inline packages/go/errorlist/error.go]: I would revert this to the old way it was being handled

File: cmd/api/src/services/graphify/tasks.go (hunk 1 above)
Comment (wes-mil) [reply cmd/api/src/services/graphify/tasks.go]: I would remove the check here at the top level for `IngestUserDataError`. 

Then instead of just slamming all the errors into `fileData.Errors`, we should loop over the errors in `graphifyError` and do an `errors.Is` or `errors.As` to tease out if the internal error is an `IngestUserDataError`.

Then we can add the error to the `UserDataErrs` or `Errors` as necessary.

File: packages/go/errorlist/error.go (hunk 2 above)
Comment (AD7ZJ) [reply packages/go/errorlist/error.go]: done!

File: cmd/api/src/services/graphify/tasks.go (hunk 1 above)
Comment (AD7ZJ) [reply cmd/api/src/services/graphify/tasks.go]: I see what you mean. I think I've fixed it now, ty for the help! I was not understanding the whole graphify error thing.

File: packages/go/errorlist/error.go [hunk 3]
```diff
@@ -62,3 +62,12 @@ func (s Error) AsStrings() []string {
...
 }
+
+// IngestUserDataError is used to return an error related to the data a user is ingesting, vs an error in the internal go logic
+type IngestUserDataError struct {
+	Msg string
+}
+
+func (e IngestUserDataError) Error() string {
+	return e.Msg
+}
```
Comment (wes-mil) [inline packages/go/errorlist/error.go]: I feel like maybe this is an error better defined in the Graphify package as it's graphify specific?

File: cmd/api/src/services/job/jobs.go [hunk 4]
```diff
@@ -146,6 +146,11 @@ func (s *JobService) CompleteAnalyzedIngestJobs() {
 					status = model.JobStatusFailed
 					message = "All files failed to ingest as JSON Content"
 				}
+			} else {
+				if job.PartialFailedFiles > 0 {
+					status = model.JobStatusPartiallyComplete
+					message = fmt.Sprintf("%d File(s) partially failed to ingest as JSON Content", job.PartialFailedFiles)
+				}
```
Comment (wes-mil) [inline cmd/api/src/services/job/jobs.go]: Cyclomatic complexity could probably be improved here?

Comment (superlinkx) [reply cmd/api/src/services/job/jobs.go]: Specifically this could be an `else if` which doesn't fix cyclo complexity technically, but it does prevent additional indentation. This function in general is gnarly and needs a refactor, but I wouldn't block this PR on it given how much else is going on.

File: packages/go/errorlist/error.go (hunk 3 above)
Comment (AD7ZJ) [reply packages/go/errorlist/error.go]: not a bad idea, let's try that.

File: cmd/api/src/services/job/jobs.go (hunk 4 above)
Comment (AD7ZJ) [reply cmd/api/src/services/job/jobs.go]: fixed!

**Review by wes-mil — APPROVED** [review]
looks good!

File: cmd/api/src/services/graphify/tasks.go [hunk 5]
```diff
@@ -179,8 +180,16 @@ func (s *GraphifyService) ProcessIngestFile(ic *IngestContext, task model.Ingest
...
 					if ok := errors.As(err, &graphifyError); ok {
-						fileData[i].Errors = append(fileData[i].Errors, graphifyError.AsStrings()...)
+						var userDataErr IngestUserDataError
+						for _, error := range graphifyError.Errors {
+							if ok := errors.As(error, &userDataErr); ok {
+								fileData[i].UserDataErrs = append(fileData[i].UserDataErrs, userDataErr.Error())
+							} else {
+								fileData[i].Errors = append(fileData[i].Errors, error.Error())
+							}
+						}
```
[the remark this answers is not in the document]
Comment (AD7ZJ) [reply cmd/api/src/services/graphify/tasks.go:192]: fixed
